notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com
            - upi.bhalla@gmail.com
            - hrani@ncbs.res.in


install:
    - sudo apt-get -y update
    - sudo apt-get -y --force-yes install python3 python-pip python3-pip
    - sudo -H pip install python-libsbml 
    - sudo -H pip install pymoose --pre 

script:
    - # Making sure no python incompatible file is added.
    - python -m compileall -q .
    - python3 -m compileall -q . || echo "Python3 is allowed to fail"
    - python -c 'import moose'
    - # More tests here for gui.
    - echo "There are not tests for gui"
